### ISSUE TITLE
False positive domains

### ISSUE THREAD

**Issue by back-to** [mitchellkrogza/Badd-Boyz-Hosts#1]
You should maybe remove this domains from the list.

- **gesangsunterricht-hh.de** / a musicschool
https://github.com/mitchellkrogza/Badd-Boyz-Hosts/blob/e4c822e9ca6ea6df7d3ea01450ad693a045fba01/hosts#L1242

- **mail.ru** / e-mail provider
https://github.com/mitchellkrogza/Badd-Boyz-Hosts/blob/e4c822e9ca6ea6df7d3ea01450ad693a045fba01/hosts#L1783

- **suche.t-online.de** / a startpage from an internet provider
https://github.com/mitchellkrogza/Badd-Boyz-Hosts/blob/e4c822e9ca6ea6df7d3ea01450ad693a045fba01/hosts#L2826

**Comment by mitchellkrogza** [comment]
Thanks for heads up will attend to in morning

**Comment by mitchellkrogza** [comment]
Fixed in https://github.com/mitchellkrogza/Badd-Boyz-Hosts/commit/5443b12687c8ee9b1462b308d4311f77b894864e
