### ISSUE TITLE
False Positive: Open Library

### ISSUE THREAD

**Issue by travismckay** [mitchellkrogza/Badd-Boyz-Hosts#10]
Hi Mitchell,

It looks like openlibrary.org is being incorrectly blocked by this list.

It is a service from the non-profit Internet Archive which provides access to public domain books.  See the Wikipedia page for more information: https://en.wikipedia.org/wiki/Open_Library

Thanks!

**Comment by TheAntimist** [comment]
I came to say this, thanks @travismckay  for putting it up before me.

**Comment by mitchellkrogza** [comment]
Will have this addressed in next commit, thanks for the heads up.

**Comment by mitchellkrogza** [comment]
Thanks @travismckay and @TheAntimist fixed in https://github.com/mitchellkrogza/Badd-Boyz-Hosts/commit/3658e87410fac528f46f3257899fab8c2244b1c9 @StevenBlack

**Comment by TheAntimist** [comment]
@mitchellkrogza Thanks for the quick work, much appreciated. Now, only if @StevenBlack, would update his list.

**Comment by StevenBlack** [comment]
@TheAntimist: done!

**Comment by TheAntimist** [comment]
@StevenBlack Thanks a lot, much appreciated.
