### ISSUE TITLE
False Positive - abc.xyz

### ISSUE THREAD

**Issue by Avicennasis** [mitchellkrogza/Badd-Boyz-Hosts#11]
abc.xyz is now a false positive - while this probably was a true positive before, Google has now bought this domain and runs it for Alphabet Inc, the new holding company of Google, Nest, et cetera.

**Comment by mitchellkrogza** [comment]
Thanks @Avicennasis fixed in https://github.com/mitchellkrogza/Badd-Boyz-Hosts/commit/4672df5ee7606da9d4525ee580b77fa4fb5eb660
