### ISSUE TITLE
False positive: fark.com

### ISSUE THREAD

**Issue by cdiv** [mitchellkrogza/Badd-Boyz-Hosts#13]
Looks like a recent update added fark.com which is... well, it's Fark. It's been around forever, I can't imagine they're resorting to referrer spamming. Thanks!

**Comment by mitchellkrogza** [comment]
Removed in https://github.com/mitchellkrogza/Badd-Boyz-Hosts/commit/462f3a5b236bdf3bc23fac0bd4cf983b72d81a9d

**Comment by mitchellkrogza** [comment]
If you want to help at all send a pull request on this file https://github.com/mitchellkrogza/Badd-Boyz-Hosts/blob/master/PULL_REQUESTS/domains.txt it is my intention to have an accurate list and not be blocking incorrect domains.
