### ISSUE TITLE
scrapy.org is an open-source python crawler

### ISSUE THREAD

**Issue by StevenBlack** [mitchellkrogza/Badd-Boyz-Hosts#15]
Hi Mitchell

[Scrapy](https://github.com/scrapy/scrapy/) is a python framework for extracting structured data from web pages.

As such it is a crawler, true, but the site itself is not malicious.

Its website, [http://scrapy.org/](http://scrapy.org/) is blocked by Badd-Boyz-Hosts.

**Comment by mitchellkrogza** [comment]
@StevenBlack fixed in https://github.com/mitchellkrogza/Badd-Boyz-Hosts/commit/78a1cf8f119782840ff3b956d11b1b282645df58 Thanks for the report.
