### ISSUE TITLE
IP Addresses

### ISSUE THREAD

**Issue by StevenBlack** [mitchellkrogza/Badd-Boyz-Hosts#18]
Hi @mitchellkrogza Mitchell, I notice the repo now contains many direct IP addresses.

I'm curious about the source of these, and how this ultimately gets curated.  I'm guessing these come from your logs?

Currently, 41 of these:

    0.0.0.0 111.68.116.106
    0.0.0.0 115.28.157.120
    0.0.0.0 138.197.2.197
    0.0.0.0 143.106.5.75
    0.0.0.0 143.95.238.62
    0.0.0.0 143.95.87.73
    0.0.0.0 150.107.73.104
    0.0.0.0 150.187.4.94
    0.0.0.0 158.69.42.211
    0.0.0.0 162.243.12.57
    0.0.0.0 174.138.54.59
    0.0.0.0 185.22.64.46
    0.0.0.0 185.46.121.67
    0.0.0.0 185.82.200.126
    0.0.0.0 200.142.99.6
    0.0.0.0 200.146.119.203
    0.0.0.0 200.148.212.234
    0.0.0.0 200.157.137.82
    0.0.0.0 200.207.9.220
    0.0.0.0 200.222.86.61
    0.0.0.0 200.241.212.23
    0.0.0.0 201.2.129.186
    0.0.0.0 201.45.142.130
    0.0.0.0 202.138.226.2
    0.0.0.0 211.32.65.138
    0.0.0.0 213.16.42.226
    0.0.0.0 213.186.33.16
    0.0.0.0 23.254.240.124
    0.0.0.0 23.91.71.251
    0.0.0.0 52.10.253.215
    0.0.0.0 59.188.15.234
    0.0.0.0 61.100.9.220
    0.0.0.0 61.96.198.20
    0.0.0.0 64.34.67.210
    0.0.0.0 66.226.22.41
    0.0.0.0 69.175.87.74
    0.0.0.0 74.200.91.98
    0.0.0.0 77.194.54.247
    0.0.0.0 93.182.168.22
    0.0.0.0 98.142.221.58
    0.0.0.0 130.211.230.53

**Comment by mitchellkrogza** [comment]
Thanks @StevenBlack those should not have slipped in there. I merged another list of mine of phishing sites into Badd Boyz. Have removed the IP's in latest commit.

**Comment by StevenBlack** [comment]
Awesome Mitchell.  I'm glad I asked :-)

**Comment by mitchellkrogza** [comment]
And glad you did 😁 sometimes my eyes play tricks on me and I miss stupid things like that.
