### ISSUE TITLE
Test list with funceble

### ISSUE THREAD

**Issue by mitchellkrogza** [mitchellkrogza/Badd-Boyz-Hosts#19]
@funilrys I set the dev version of funceble loose on this repo. Let's see.
Some weird output from some whois results, see - https://travis-ci.org/mitchellkrogza/Badd-Boyz-Hosts/builds/265582291

**Comment by mitchellkrogza** [comment]
@funilrys 40 minutes into Travis build and only on "m" ..... not going to make it 😁

**Comment by mitchellkrogza** [comment]
@funilrys .... reached until "rel" then maxed out due to the 50 minute timeout.

**Comment by funilrys** [comment]
@mitchellkrogza Before anything thanks! I planned to test with dead-hosts but this is just an awesome output :)

**Comment by funilrys** [comment]
The idea behind the auto save is to commit the continue.txt + all generated files then when you restart with all save files, it'll continue from the last saved domain/IP :)  

Not bad at all "rel" :)

For me, the main issue is the outputs like https://travis-ci.org/mitchellkrogza/Badd-Boyz-Hosts/builds/265582291#L9807 :smile:

**Comment by funilrys** [comment]
@mitchellkrogza You can restart it :) Only the "m" issue have an influence with the Travis autosave :) The whois outputs don't have any influence with the result :wink:

**Comment by mitchellkrogza** [comment]
Ok so how we do that? I'd like to test that for sure but think I am going to need some script changes in deploy etc ???

**Comment by funilrys** [comment]
For now, we need to start from beginning because `commit -am` did not work.

Than, we need only a commit so Travis restart its job ... But you're right I didn't really think about how we handle that part ...

**Comment by mitchellkrogza** [comment]
Going to have to re-work a lot of scripting so that it commits "without a [ci skip]" ... which will then tell Travis to go ahead and build again "but" this time continuing .... and keep doing this until it reaches the end of a list .... then move to final deploy with a [ci skip] message. This one's going to be tricky one to figure out.

**Comment by mitchellkrogza** [comment]
Oh yes, BTW, I found this awesome free app for iOS. https://itunes.apple.com/ua/app/codehub-a-client-for-github/id707173885?mt=8 I did two commits from my iPad last night which was a total breeze, absolutely brilliant little app.

**Comment by funilrys** [comment]
The big problem is that sometimes Travis stops at [40-50] minutes ...

Not bad :+1:

**Comment by mitchellkrogza** [comment]
We will need to have YET another switch for funceble 😹  setting a -r (runtime) option and set it to 25 minutes, then commit and carry on.

👍  that Codehub app is awesome, I could sit in front of TV and do 2 quick commits with the greatest of ease. NOW .... when I go away for 12 days I can be GITTING all I like 🤣  🤣  .... Dylan would KILL ME if I did that.

**Comment by funilrys** [comment]
Or we stop Travis by exiting after 40 minutes :joy_cat:

**Comment by mitchellkrogza** [comment]
40 is good. To be safe I would go with 35 and not put Travis under too much pressure as some of our repo's tend to do 😹  .... one day I can see an email saying hey, slow down on Travis 🤣

**Comment by funilrys** [comment]
Then we need to handle the end of the file :smile_cat:

**Comment by mitchellkrogza** [comment]
What about 
- funceble with a runtime of let's say 40 minutes. 
- When 40 minutes lapses, funceble kills itself, writes the continue.txt file
- Do a travis commit of all files without [ci skip] in the commit message
- Travis then will trigger a new build
- New build starts, funceble kicks in and continues from continue.txt
- 40 minutes ... same thing.
- Once funceble gets to the end of a list it should maybe write a `.complete` file
- The final deploy script can search for the existence of `.complete` and then do the final commit with [ci skip]

Handling this logic in .travis.yml deploy section is what is going to be the trouble maker ???

**Comment by funilrys** [comment]
What about

* Funceble run 40 minutes 
  * After 40 minutes:
    * We commit without [ci skip]
    * We exit the script with `exit 0`

Then on next commit (last one)
* Funceble run for 40 minutes
   * If we reach the last line we set a variable which gonna activate the commit with [ci skip]

**Comment by funilrys** [comment]
https://github.com/travis-ci/travis-build/blob/f603c0089116364ccb820cad790b0837f358fb53/lib/travis/build/templates/header.sh#L163-L167 :smile:

**Comment by mitchellkrogza** [comment]
You have collaborator access to this repo .... so you can test anything you like here. I'm busy with a cleanup right now of some false positives and dead / inactive domains.

**Comment by mitchellkrogza** [comment]
@funilrys I ran this list on my Ubuntu Server this morning with a timeout of 5 seconds. It finished now.

```
Execution Time:
04:43:37
```

I also ran it as follows but cannot find any percentage.txt file anywhere `./funceble -a -ex -h -p -t 5 -f domains.txt` ???

I ran it using the dev branch.

**Comment by mitchellkrogza** [comment]
Scratch that @funilrys i should not have added the -p switch ..... silly me.

**Comment by funilrys** [comment]
That is the reason I added `Current value: xxxx` into `./funceble --help` :joy_cat: :joy_cat: :joy_cat: :joy_cat:

**Comment by mitchellkrogza** [comment]
@funilrys running new dev branch now.

**Comment by mitchellkrogza** [comment]
Closing, working 100%
