### ISSUE TITLE
[Funceble] Result of execution

### ISSUE THREAD

**Issue by funilrys** [mitchellkrogza/Badd-Boyz-Hosts#2]
Hello @mitchellkrogza ,

As you know I released and still continue to develop [Funceble](https://github.com/funilrys/funceble).

I wanted to help, so you can find here the result of my last execution against your list.

[Badd-Boyz-Hosts@mitchellkrogza](https://github.com/funilrys/dead-hosts) ==> Badd-Boyz-Hosts :x:

Have a nice day/night.

Cheers,
Nissar Chababy

**Comment by mitchellkrogza** [comment]
Awesome, well done 👍  That's really great.
I've forked that locally and will keep that as part of my regular tests. Very nicely written script and to my surprise not too may dead domains on my list 😄

**Comment by funilrys** [comment]
Thank you :smiley_cat: 
I was surprised too! I'm not done with other lists but for now your lists have the best ratio :smiley: 

Glad to help and in between the version 1.1.0 is coming a the end of the week or next monday :)

**Comment by mitchellkrogza** [comment]
Going to be very interesting to see the results of all the other lists merged into https://github.com/StevenBlack/hosts

**Comment by funilrys** [comment]
After 6 hours (I paused there) I get 169 inactive ... 
It's gonna take +9 hours to test them so gonna restart it in an hours after fixing some bugs ...

**Comment by mitchellkrogza** [comment]
I ran a similar script locally on my Mac, just doing nslookups and logging them to a file. It ran for nearly 7 hours I think.

**Comment by funilrys** [comment]
I decided to test them separatly so I just released [adaway.github.io@AdAway](https://github.com/funilrys/dead-hosts) :wink:

**Comment by funilrys** [comment]
Just a [referencement](https://github.com/StevenBlack/hosts/issues/259)! :wink: 

and by the way, I released other lists

**Comment by funilrys** [comment]
@mitchellkrogza As a user of my script, if you don't mind, I want your opinion about the referenced link...

**Do you think that a python script will be better than a bash?** 

I don't want to lost time rewriting an `updateHostsFile.py` if it's unusable in the end.
Actually, all things I wrote in bash are not that easy to implement into **an existing python** script which doesn't read all domains one by one ...

I do prefer **BASH** over **python** but I want to have more opinions about this question.


I don't want to rest with:
> "IMO good idea is MERGE this functionality directly in updateHostsFile.py code but main code is now in BASH: https://github.com/funilrys/funceble/blob/master/funceble"

Thanks in advance

Cheers

**Comment by mitchellkrogza** [comment]
I prefer bash, always works and is truly universal. If it works in bash leave it that way.

**Comment by funilrys** [comment]
Soo true, except for windows users who are not in developer mode since about a week :smile_cat: 

Did you notice[ the following](https://msdn.microsoft.com/de-de/commandline/wsl/about) (a bit out of topic)?

**Comment by mitchellkrogza** [comment]
Windows .... whats that's that 🥀  😂 

LOL, love your link .... bash on windows ..... are Microsoft finally realizing what they've been missing out on all these years 😹

**Comment by funilrys** [comment]
Same reaction when I saw it on twitter :joy_cat: I was like: "what's going on !?" :joy: 
Then I saw [another link](https://blogs.technet.microsoft.com/windowsserver/2015/05/06/microsoft-loves-linux/) in comments which made me think that they may don't want windows anymore :smile_cat:

**Comment by mitchellkrogza** [comment]
![screen shot 2017-03-08 at 8 22 23 am](https://cloud.githubusercontent.com/assets/9961541/23692652/a6bb35ee-03d8-11e7-9151-09e4ea5a32ea.png)
Now I've heard it all 😂

**Comment by funilrys** [comment]
:smile_cat: Long life to Linux :heart: :smiley_cat: 
Released the [1.2.0 of funceble ](https://github.com/funilrys/funceble/releases/tag/1.2.0) this afternoon!!!

**Comment by funilrys** [comment]
Hello @mitchellkrogza ,

You can find here the result of my last execution against your list.

[Badd-Boyz-Hosts@mitchellkrogza](https://github.com/funilrys/dead-hosts/tree/master/Badd-Boyz-Hosts%40mitchellkrogza) ==> Badd-Boyz-Hosts :x:

Have a nice day/night.

Cheers and long life to open source :smile_cat: :wink:

**Comment by mitchellkrogza** [comment]
Awesome, seems my list is nice and clean 👍

**Comment by funilrys** [comment]
Yeah and now you can perform a test with the following from your directory :wink: 

```bash
./tool -c > /dev/null
```

This will download your list and test it against funceble :100: :smile_cat:
