### ISSUE TITLE
False Positive > suche.t-online.de

### ISSUE THREAD

**Issue by mitchellkrogza** [mitchellkrogza/Badd-Boyz-Hosts#22]
As Per: https://github.com/mitchellkrogza/nginx-ultimate-bad-bot-blocker/issues/34

should be removed because it is the site of a common german ISP who sets his homepage as the starting page in the browser which causes the people to use their search site and get to the resulting page with this referrer. They also provide an modified browser which might also send this referrer.

**Comment by funilrys** [comment]
Well it's actually the first German ISP :joy:

**Comment by mitchellkrogza** [comment]
Actually already been removed from Badd Boyz in prior request some months ago 😁 Closing

**Comment by funilrys** [comment]
You should create a script to search the occurrence + remove + add into a private database :)

**Comment by mitchellkrogza** [comment]
You mean like a false-positives.txt file which can be checked on any future build and remove if any of them mistakenly get re-added?

**Comment by funilrys** [comment]
yes for example :+1:

**Comment by mitchellkrogza** [comment]
Great idea, will implement it. Will be sure to save lots of curation issues in the future 👍

**Comment by mitchellkrogza** [comment]
And think I will centralize it somewhere so my other repo's can reference it too.
