### ISSUE TITLE
False Positive

### ISSUE THREAD

**Issue by timmyRS** [mitchellkrogza/Badd-Boyz-Hosts#3]
The Github.io Site of FontAwesome (`fortawesome.github.io`) is being falsely [blocked by the list](https://github.com/mitchellkrogza/Badd-Boyz-Hosts/blob/master/hosts#L1281).

**Comment by mitchellkrogza** [comment]
Thanks for alerting me to that fixed in https://github.com/mitchellkrogza/Badd-Boyz-Hosts/commit/ff3666ae0509c1506b7f0bafe9ad581434c6fbb2 not sure how that ever got in there, must have been one of my mornings when I had no glasses for about 2 weeks 😊
