### ISSUE TITLE
False Positives / Incorrectly Blacklisted Domains ?

### ISSUE THREAD

**Issue by mitchellkrogza** [mitchellkrogza/Badd-Boyz-Hosts#5]
If you ever find any false positives or blacklisted domains that you believe should not be blacklisted on this blocker please list them separately as issues here explaining why they should not be on the blocker and they will be investigated and promptly removed if found to be valid removals.

Unfortunately this list started over a year ago which was originally based on a few other lists which did contain a few false positives. Most have been ironed out over the past few months thanks to issues noted on this and other repo's I run or contribute to. 

The original list from where this began had a mere 200+ listings which now has grown into over 3800+ strong which has been built day by day through monitoring of my servers logs of 18 very busy web sites. So yes there may be a few remnants from the original list which do not belong here. I have spent into the thousands of hours building this blocker and maintaining this list.

It is NOT the intention of this blocker to block out valid domains and services and I maintain a very clean list which is also regularly tested for dead domains and expired domains which are also removed every now and again to keep the list clean and functional as it should be.

So if you find anything being blocked that you believe is unwarranted, kindly list it here under issues and the matter will be looked into and promptly attended to.

**Comment by bakaoniisan** [comment]
nordvpn.com is a vpn site. No idea of why it would be on this list. Weird.
Thanks.

**Comment by mitchellkrogza** [comment]
Thanks fixed in https://github.com/mitchellkrogza/Badd-Boyz-Hosts/commit/d7d783d4e08b7a8dbc1b9f7225552bf17f7dee6f thanks for your contribution

**Comment by mitchellkrogza** [comment]
@StevenBlack we now have a very nice control mechanism in place for dealing with whitelisted domains, false positives and dead domains at 
https://github.com/mitchellkrogza/CENTRAL-REPO.Dead.Inactive.Whitelisted.Domains.For.Hosts.Projects now we have central control over preventing anything ever getting re added by mistake and also ridding these lists of dead and inactive domains

**Comment by hotota** [comment]
This is machine translation. I am sorry that it is hard to read.

"goo.ne.jp" is not a virus / fake news site.Please correct it.
Thanks.

**Comment by mitchellkrogza** [comment]
Thanks for reporting @hotota it has been fixed in https://github.com/mitchellkrogza/Badd-Boyz-Hosts/commit/186984d2c8050c934483070be0063c4e0c760773 please list all future false positives as separate issues and not inside this issue as it it easier track issues.

**Comment by hotota** [comment]
@mitchellkrogza Thank you for fixing quickly.

**Comment by mitchellkrogza** [comment]
:+1: no problem I always try and keep things up to date and fixed fast. Thanks for reporting it.

**Comment by ghost** [comment]
`openallurls.com`
It's a legit tool I've used many times.

Thanks for this project by the way. :+1:

**Comment by mitchellkrogza** [comment]
Thanks @IDKwhattoputhere addressed in latest Build which should be complete shortly. :+1:

**Comment by ghost** [comment]
Thanks a bunch.

`yougetsignal.com`
Have used this tool many times: `https://www.yougetsignal.com/tools/web-sites-on-web-server/`
Seems like a legit site.

**Comment by mitchellkrogza** [comment]
Thanks @IDKwhattoputhere has been removed in latest commit, new build in progress.

**Comment by gianmaxfactor** [comment]
there is no www.amaporn.com, only amaporn.com

**Comment by alanfranz** [comment]
digilander.libero.it is a site hosting personal user pages and blogs, something like the old geocities. The site itself is totally legit, although since it's got little moderation it may host questionable content sometimes.

**Comment by alanfranz** [comment]
@mitchellkrogza  any update on removing digilander.libero.it ?

**Comment by mitchellkrogza** [comment]
Hi @alanfranz it has been addressed in latest build currently in progress.

**Comment by Najoj** [comment]
I noticed that brakrock.be is on the list, but the address belongs to a Belgian music festival.

**Comment by funilrys** [comment]
Hi @Najoj and thanks for your contribution.
It should be removed once the current build process is finished.

**Comment by misteranonimous** [comment]
mangadex.com is a site which hosts Japanese comics. A minority of the content is erotic, but these require login and are inaccessible to guests. The site does not contain ads or viruses and is not malicious in any way.

**Comment by funilrys** [comment]
Hi @misteranonimous and thanks for your contribution.
It's removed from `hosts` and `PULL_REQUESTS/domains.txt`

**Comment by ghost** [comment]
`gigablast.com` is an open-source search engine. https://en.wikipedia.org/wiki/Gigablast

**Comment by mitchellkrogza** [comment]
Closing this topic so that false positives can be listed as individual issues and not in here.
