### ISSUE TITLE
fok.nl

### ISSUE THREAD

**Issue by bertpoort** [mitchellkrogza/Badd-Boyz-Hosts#50]
fok.nl should not be listed, it is a Dutch news site.

**Comment by mitchellkrogza** [comment]
@bertpoort @funilrys please see

![fok2](https://user-images.githubusercontent.com/9961541/42764692-85ce4046-8916-11e8-9ec9-0cad17f71a2f.PNG)

![fok1](https://user-images.githubusercontent.com/9961541/42764700-8bb1d5ae-8916-11e8-932d-a4d8a5d7b0c5.PNG)

**Comment by funilrys** [comment]
I'm not ready to whitelist that because of that last picture! But it still looks like a legit new page with some strange banners ... 

Also it redirects to http://frontpage.fok.nl/ so not whitelisting. 

Feel free to take a decision based on that, I'll apply @mitchellkrogza !
