### ISSUE TITLE
maxthon.com

### ISSUE THREAD

**Issue by Crystal-RainSlide** [mitchellkrogza/Badd-Boyz-Hosts#59]
maxthon.com itself is Maxthon browser's site. you should block:
```
stat-c.maxthon.com
dcs.maxthon.com
```
instead.

**Comment by funilrys** [comment]
Hi @Crystal-RainSlide and thanks for the suggestion!


May I invite you to create a PR for the addition [here](https://github.com/mitchellkrogza/Badd-Boyz-Hosts/blob/master/PULL_REQUESTS/domains.txt) and a PR for the whitelisting [here](https://github.com/Ultimate-Hosts-Blacklist/whitelist/blob/master/domains.list) ?

Thanks in advance.

Have a nice day/night.

Cheers,
Nissar
