### ISSUE TITLE
False Positive: Weebly.com

### ISSUE THREAD

**Issue by timmyRS** [mitchellkrogza/Badd-Boyz-Hosts#6]
Weebly itself is a free hosting provider.

**Comment by mitchellkrogza** [comment]
Thanks @timmyrs for the heads up. An old remnant from my original list I started from a year ago. Removed in https://github.com/mitchellkrogza/Badd-Boyz-Hosts/commit/1b562d40064df0d9267f0965400d6f8c58208109 @StevenBlack

**Comment by StevenBlack** [comment]
Thanks @mitchellkrogza, done!
