### ISSUE TITLE
add xorcan hosts

### ISSUE THREAD

**Issue by ghost** [mitchellkrogza/Badd-Boyz-Hosts#66]
take a look.

https://github.com/xorcan/hosts
https://github.com/xorcan/hosts/blob/master/xhosts.txt
https://raw.githubusercontent.com/xorcan/hosts/master/xhosts.txt

**Comment by mitchellkrogza** [comment]
Nice work, I'd be happy to merge this into Badd Boyz.

**Comment by mitchellkrogza** [comment]
@xorcan can you create a separate list of just phishing links too? 

Then I can pull your phishing data into https://github.com/mitchellkrogza/Phishing.Database

The format needs to be the full url just one per line. Would be a great addition to have more phishing data in our database.

http://thelink.com/?whatever
https://anotherlink.com/?whatever
http://andanotherlink.com/?whatever

**Comment by ghost** [comment]
@mitchellkrogza i will try later thank you :) 

_OnePlus 5 cihazımdan [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) kullanılarak iletildi._

**Comment by mitchellkrogza** [comment]
Great let me know, you can also just start from today with all new phishing you find and my scripts will just pull from your repo every hour when I run tests.

**Comment by spirillen** [comment]
hi @xorcan nice work, is there are change you could translate the README.md into English, then I would be interestet to as @mitchellkrogza is to add your work to my [external list](https://gitlab.com/my-privacy-dns/external-sources/hosts-sources)

**Comment by funilrys** [comment]
If I'm not wrong (Let me know if I'm wrong), xorcan was merged into the StevenBlack's hosts project. 

So merging this may create some huge duplicates for end-user ... (Most users of this list are behind @spirillen's project, Steven's project or @ultimate-hosts-blacklist)

Therefore, I'm closing this. 

Let me know if something is wrong with my statement.

Cheers, 
Nissar.
