### ISSUE TITLE
Request for Blacklist: fakeshops (multiple domains)

### ISSUE THREAD

**Issue by Somebodyisnobody** [mitchellkrogza/Badd-Boyz-Hosts#68]
Hello, the following URLs contains fake shops, described on [YouTube - Sempervideo](https://www.youtube.com/watch?v=V9_EQcDQ9-A) (german):
www.freudebote.de
www.poponuss.de
www.saltdays.de
www.hallohaus.co
www.megahause.de

In short, these shops grew from one template with the same goods, have giant discounts, you have suspicous payment methods and some websites have no imprint. **The sites have the same DNS-A records!**

Ultimate-Hosts-Blacklist/dev-center#40

**Comment by Somebodyisnobody** [comment]
Sorry, could you please remove the label from this issue, that happened cause of the Issue-form

**Comment by mitchellkrogza** [comment]
![2019-10-17_10-48](https://user-images.githubusercontent.com/9961541/66993176-6c72c900-f0cb-11e9-982c-cda83f91c658.png)
![2019-10-17_10-47_1](https://user-images.githubusercontent.com/9961541/66993178-6d0b5f80-f0cb-11e9-9351-e36c7ce0b3cc.png)
![2019-10-17_10-47](https://user-images.githubusercontent.com/9961541/66993179-6d0b5f80-f0cb-11e9-8507-39afe02ab269.png)
![2019-10-17_10-46](https://user-images.githubusercontent.com/9961541/66993181-6da3f600-f0cb-11e9-86be-74f86109c6da.png)
![002](https://user-images.githubusercontent.com/9961541/66993184-6da3f600-f0cb-11e9-8d2d-177944738942.png)

**Comment by mitchellkrogza** [comment]
Thank you @Somebodyisnobody added in latest commit.

**Comment by mitchellkrogza** [comment]
All these domains are listed on Phishtank
