### ISSUE TITLE
False positives: SEO backlink checker

### ISSUE THREAD

**Issue by alfoeternia** [mitchellkrogza/Badd-Boyz-Hosts#7]
These SEO backlink checker (& more) websites shouldn't be in the list:
- ahrefs.com
- moz.com
- semrush.com

Afaik all of them respect good practices

**Comment by mitchellkrogza** [comment]
@alfoeternia Agreed, I will remove them on my next commit and start running a separate domain list for Badd-Boyz. 

For my bot blocker's, where this list is drawn up  from, will they stay in place as I use them to keep competitors from backlink scanning but I do agree as includes in a hosts file not required.

I am however probably not going to remove any of the domains related to Semalt as they do not respect good practices whatsoever.

**Comment by mitchellkrogza** [comment]
Thanks @alfoeternia removed in https://github.com/mitchellkrogza/Badd-Boyz-Hosts/commit/1b562d40064df0d9267f0965400d6f8c58208109 let me know if you spot any more or send a Pull Request in the PULL_REQUESTS folder. @StevenBlack please take note of new updates.
