### ISSUE TITLE
Add nokia-n8.com

### ISSUE THREAD

**Issue by Somebodyisnobody** [mitchellkrogza/Badd-Boyz-Hosts#72]
nokia-n8.com
and track.nokia-n8.com

Sends spam-mails (see screenshot), no imprint, no privacy statement, whois cloaked
![Spam-Mail](https://user-images.githubusercontent.com/35230554/67693442-fc552480-f9a1-11e9-86c0-1d689a2629d5.png)
![web_startpage](https://user-images.githubusercontent.com/35230554/67693438-fbbc8e00-f9a1-11e9-923f-b878aa06d3df.png)
![web_terms](https://user-images.githubusercontent.com/35230554/67693448-fc552480-f9a1-11e9-9637-75fe21b50cd4.png)
![web_privacy](https://user-images.githubusercontent.com/35230554/67693440-fc552480-f9a1-11e9-87bf-62008009a15f.png)
![whois](https://user-images.githubusercontent.com/35230554/67693446-fc552480-f9a1-11e9-98f9-1da582cfe739.png)

Please report on PrivacyGuardian.org like I did!
If you want annoy them, report to the Berliner Datenschutzbeauftragte für Datenschutz und Informationsfreiheit. (data protection officer for data protection and freedom of information)
I can redirect the mails I got on request.

**Comment by spirillen** [comment]
Is this cumming from a web-mail?

```
dig nokia-n8.com -t TXT +short
"v=spf1 a mx ptr a:nokia-n8.com ip4:162.218.211.224/27 ?all"
```

**Comment by funilrys** [comment]
@Somebodyisnobody Zumindest sind die lustig zu lesen, wenn die Hintergrundbilder fehlen :joy: 

Will probably be blocked by Mitch @mitchellkrogza  in the coming hours (probably can't promess). From my side, it can be added to the list.

**Comment by spirillen** [comment]
Pass aus meine Herren ich sprechen auch deutsch :+1:

**Comment by funilrys** [comment]
Oww suppi 😎
