### ISSUE TITLE
Add maincert.com

### ISSUE THREAD

**Issue by Somebodyisnobody** [mitchellkrogza/Badd-Boyz-Hosts#74]
https://maincert.com/
https://track.maincert.com/

same as #72 sending spam mails to

**Comment by spirillen** [comment]
Hi @Somebodyisnobody could you provide more info on what and how this is used, like screendumps you made in #72 ?

And you are also welcome to trow a copy to my [matrix](https://gitlab.com/my-privacy-dns/matrix/matrix/) I would love to block this kind :smiling_imp:

**Comment by Somebodyisnobody** [comment]
I am really too lazy to do that because it's just the same mail with other bait:
![m](https://user-images.githubusercontent.com/35230554/68493176-45339580-024c-11ea-94c3-16fde8d68651.png)
So you see that was wasted time, it's exactly the same :)

How does matrix work, what do you need for that?

**Comment by Somebodyisnobody** [comment]
I am really thinking about an addon fpr TB which checks the ultimate blacklist against incoming mails and has the possibility to upload masked mail snippets that are marked as spam by the user. Other clients could compare this masked snippets to their incoming mails to be warned...
How do you feel about this @mitchellkrogza?

**Comment by spirillen** [comment]
Matrix in a nutshell https://gitlab.com/my-privacy-dns/matrix/matrix/blob/master/CONTRIBUTING.md

1. You have something to share for blocking
1. You create a Issue, using a template from the drop-down that match you commit
1. Make some good points, documentations for your submission (It's our history of why stuff is added there)
1. Add your commit to the source/"group"/*.list that match your level of submission (single vs wildcard domain)
 1. Now everyone who likes to, have a clean list of sources to what ever they like. nobody need to first clean up a lot of data etc.

Personally I use it with the CI to generate other output formats as eg. Hosts and Unbound as I manually add records to my RPZ zones :) so any documented/argumented domain is welcome :smiley: 

<blockquote><img src="/uploads/-/system/project/avatar/12520650/the-matrix-256.png" width="48" align="right"><div>GitLab</div><div><strong><a href="https://gitlab.com/my-privacy-dns/matrix/matrix/blob/master/CONTRIBUTING.md">CONTRIBUTING.md · master · My Privacy DNS Firewall / Matrix / Matrix</a></strong></div><div>The complete Blocking lists</div></blockquote>

**Comment by Somebodyisnobody** [comment]
Oh I understand. I thought it's an automated blacklisting and wanted to ask how to detect it with different domains. I thought maybe you use the used HTML code as template or something else.

**Comment by spirillen** [comment]
No matrix is the base source for automation :) in https://gitlab.com/my-privacy-dns/rpz-dns-firewall-tools

And when a submission is merged into the master, then the API tells the CI in https://gitlab.com/my-privacy-dns/rpz-dns-firewall-tools to startup and generate new list
<blockquote><img src="/uploads/-/system/group/avatar/5188133/RPZ_DNS_firewall_tools.png" width="48" align="right"><div>GitLab</div><div><strong><a href="https://gitlab.com/my-privacy-dns/rpz-dns-firewall-tools">RPZ DNS firewall tools</a></strong></div><div>This group consist of different tools and scripts to set various DNS Firewalls on different DNS Server My Privacy DNS</div></blockquote>
