### ISSUE TITLE
Add spacebridemag.com

### ISSUE THREAD

**Issue by Somebodyisnobody** [mitchellkrogza/Badd-Boyz-Hosts#76]
spacebridemag.com
track.spacebridemag.com
exactly the same as #72, #74, #75, same design, same website template

**Comment by funilrys** [comment]
Can you create a PR? Will go faster as it's just a matter of margin after checking (for us) :wink: 

Cheers, 
Nissar

**Comment by spirillen** [comment]
Thanks for [sharing](https://gitlab.com/my-privacy-dns/matrix/matrix/issues/673) @Somebodyisnobody

**Comment by Somebodyisnobody** [comment]
@funilrys do i need to change all the 22 files like f8cf5b7658d1e5cb857248cdba10b4b195938119?

**Comment by funilrys** [comment]
@Somebodyisnobody nope it's all into https://github.com/mitchellkrogza/Badd-Boyz-Hosts/tree/master/PULL_REQUESTS the rest ist just automation with [PyFunceble](https://pyfunceble.github.io/).

<blockquote><img src="https://avatars2.githubusercontent.com/u/9961541?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/mitchellkrogza/Badd-Boyz-Hosts">mitchellkrogza/Badd-Boyz-Hosts</a></strong></div><div>A hosts file for use on any operating system to block bad domains out of your servers or devices. - mitchellkrogza/Badd-Boyz-Hosts</div></blockquote>
