### ISSUE TITLE
[BUG] Hosts list is now just one domain

### ISSUE THREAD

**Issue by StevenBlack** [mitchellkrogza/Badd-Boyz-Hosts#79]
Hi Mitchell!  The Badd-Boyz-Hosts contains just one domain right now.

😉

**Comment by dnmTX** [comment]
**PING** @funilrys. Also noticed that many are failing to filter. Please check that as well.Thanks 👍

**Comment by mitchellkrogza** [comment]
Seems to be fixed now @StevenBlack something very weird happened in the Travis-CI environment but @funilrys seems to have it sorted now
