### ISSUE TITLE
[FALSE-POSITIVE] 

### ISSUE THREAD

**Issue by Dubz** [mitchellkrogza/Badd-Boyz-Hosts#81]
**Domains or links**
networkcheck.xyz

**More Information**
How did you discover your web site or domain was listed here?
1. Domain was recently purchased, and saw a high number of requests. Logged requests, found them linking to js files and `/metric/`. Apparently it was used maliciously in the past. Domain is now under new ownership, and will no longer be used maliciously. Cloudflare has already unblocked it, and it is running through their infrastructure.
1. Alias domains include: [internetcheck.xyz](internetcheck.xyz), [internettest.xyz](internettest.xyz), and [networktest.xyz](networktest.xyz).
1. Currently cloned similar to [neverssl.com](neverssl.com), for similar reasons, until a remake is completed.

Apparently I'll have to continue hunting down different lists that has this included to have it removed, since this is the second one I've found. It wasn't causing problems for me, I'm just researching more about it to see if I can try to eradicate the malware some.

**Comment by dnmTX** [comment]
@Dubz  `networkcheck.xyz` doesn't appear to be listed here nor any of the aliases mentioned in your post.
Check your sources please,or better yet,UPDATE your lists.

**Comment by Dubz** [comment]
@dnmTX, I found the domain listed in commit https://github.com/mitchellkrogza/Badd-Boyz-Hosts/commit/b78e04fff43f09725f08d45253e2ff8191529278, but it doesn't appear to be on the files currently. Not sure why I cannot find them elsewhere but here. I'll close this out, though.
