### ISSUE TITLE
Please add this websites to the hosts list

### ISSUE THREAD

**Issue by GEssay** [mitchellkrogza/Badd-Boyz-Hosts#82]
I use stevenblack unified blacklist and this websites arent there although they are pornography. Here are the sites 
https://pastebin.pl/view/54df1351

**Comment by spirillen** [comment]
This lists do not handle these kind of requests, if I remember it right, but there are other very good places to add these.

Here is 3 suggestions:
1 <https://github.com/Clefspeare13/pornhosts>
2 <https://github.com/Import-External-Sources/pornhosts>
3 <https://www.mypdns.org/maniphest/task/edit/form/2/> (Closed form, login with your GH. Required for not mixing the domain with adult contents on search-engines)

Just fill the issue templates, then you have  at least a bi-weekly merge of submissions

<blockquote><img src="https://avatars3.githubusercontent.com/u/23044484?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/Clefspeare13/pornhosts">Clefspeare13/pornhosts</a></strong></div><div>An anti porn hosts file. Contribute to Clefspeare13/pornhosts development by creating an account on GitHub.</div></blockquote>
<blockquote><img src="https://repository-images.githubusercontent.com/220451309/4388f200-43a3-11ea-8eaa-775c60f17008" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/Import-External-Sources/pornhosts">Import-External-Sources/pornhosts</a></strong></div><div>Pornhosts a hosts-file formatted file of the RPZ zone file  - Import-External-Sources/pornhosts</div></blockquote>
<blockquote><div><strong><a href="https://www.mypdns.org/maniphest/task/edit/form/2/">Login</a></strong></div></blockquote>

**Comment by GEssay** [comment]
ok, thanks

**Comment by funilrys** [comment]
Thanks @spirillen for the follow-up. It's true if you are coming from Steve's list, you should report to https://github.com/Clefspeare13/pornhosts.

Stay safe and healthy.
Nissar

<blockquote><img src="https://avatars3.githubusercontent.com/u/23044484?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/Clefspeare13/pornhosts">Clefspeare13/pornhosts</a></strong></div><div>An anti porn hosts file. Contribute to Clefspeare13/pornhosts development by creating an account on GitHub.</div></blockquote>
