### ISSUE TITLE
[BUG] Hosts file has just one host?

### ISSUE THREAD

**Issue by StevenBlack** [mitchellkrogza/Badd-Boyz-Hosts#85]
Hi Mitchell!

Since commit 7ef4442508d0b96 on February 17th the hosts file is basically empty?  Bug?

**Comment by mitchellkrogza** [comment]
Thanks for the heads up Steven fixed in https://github.com/mitchellkrogza/Badd-Boyz-Hosts/commit/85966b95e2cdfbdad3b171eba882f89009eb8e54 someone sent a PR addition but instead of adding to the file only a single entry was sent. My bad completely slipped past me.
