### ISSUE TITLE
Empty hosts file

### ISSUE THREAD

**Issue by StevenBlack** [mitchellkrogza/Badd-Boyz-Hosts#88]
Hi Mitchell,

The hosts file is almost empty?  Just one host?

https://raw.githubusercontent.com/mitchellkrogza/Badd-Boyz-Hosts/master/hosts

Thanks!

**Comment by mitchellkrogza** [comment]
Apologies @StevenBlack have fixed for now, trying to isolate why they go missing upon every addition.

**Comment by mitchellkrogza** [comment]
Hi @StevenBlack it's now properly fixed, was a silly bug.

**Comment by StevenBlack** [comment]
Thank you Mitchell @mitchellkrogza !  Keep up the good fight!
