### ISSUE TITLE
[FALSE-POSITIVE] domain: amospalla.es

### ISSUE THREAD

**Issue by amospalla** [mitchellkrogza/Badd-Boyz-Hosts#90]
**Domains or links**
amospalla.es

**More Information**
I am the owner of this domain, I discovered it is blocked by using an ads DNS block service.

I use this domain for personal stuff and I don't know what is the reasone behind it being blocked. I may have been hacked in the past but I've got no idea of why the domain is blocked nowadays.

**Have you requested removal from other sources?**
I've also asked for removal on https://oisd.nl, where I initally discovered I am blocked.

Thank you.

**Comment by mitchellkrogza** [comment]
Most likely because your website was hacked @amospalla

**Comment by amospalla** [comment]
Thank you very much! :)

**Comment by amospalla** [comment]
The subdomain www.amospalla.es was also blocked, didn't notice and so didn't report originally. Could you please also remove it?

Moreover, is it posible to remove both amospalla.es and www.amospalla.es from the hosts file? A couple of months ago you removed the domain amospalla.es from the file named _domains_, but it is still listed in the file named _hosts_.

Thank you.

**Comment by mitchellkrogza** [comment]
Fixed in

https://github.com/mitchellkrogza/Badd-Boyz-Hosts/commit/626748c5a3ecf8f4e46ce6a2d3139642223fb77f

https://github.com/mitchellkrogza/Badd-Boyz-Hosts/commit/a522fecffc5ed9e6e74b08cc2757a7c0b296b0d0

https://github.com/mitchellkrogza/Badd-Boyz-Hosts/commit/409c7ebf5c48d399c66ac76a63cd738bf076331e

**Comment by amospalla** [comment]
Thank you very much.
