### ISSUE TITLE
[Domain ADDITION] 

### ISSUE THREAD

**Issue by Dzuelu** [mitchellkrogza/Badd-Boyz-Hosts#91]
**Domains or links**
Please list any domains and links listed here which you believe should be added.
- applecareonline.com

**More Information**
How did you discover your web site or domain was listed here?
1. Was redirected to this url by mis-typing, not sure what I mis-typed though.

**Have you requested removal from other sources?**
Please include all relevant links to your existing removals / whitelistings.
Reported to google, microsoft, norton report pages that I found.

**Additional context**

:exclamation: This site creates an alert continuously and will try to send a `tele:xxx-xxx-xxxx` with a number for a scam. Adding this here so it will be picked up in my pihole eventually. 

NOTE: There is also no addition template, may be beneficial to add.

**Comment by spirillen** [comment]
Do you happens to have the full url and can you confirm if this is still active, I've got blocked in there vanish proxy.

If still active, would you please report the domain [here](https://0xacab.org/my-privacy-dns/matrix/-/issues/new?issue[issue_type]=issue&issuable_template=Scamming) as well for faster commit you can add `ping @spirillen` as reply to the report
